DECLARE 
@service VARCHAR(30)  = 'Gym',
@client int = 29,
@comming datetime = '01-12-2018'

EXEC AddServices_sp  @service, @client, @comming

SELECT * FROM ADDSERVISE
SELECT * FROM CLIENTSERVICE
SELECT * FROM RESERVATION

DELETE FROM CLIENTSERVICE

SELECT COUNT(*) FROM RESERVATION WHERE RESERVATION.CLIENT_ID = 29 AND RESERVATION.COMMING = '01-12-2018'