DECLARE
@cid int,
@sid int,
@actual bit,
@i int = 1
BEGIN
BEGIN TRANSACTION
	WHILE @i <= 100000
	BEGIN
		SET @cid = ROUND(RAND()*10000,0)
		SET @sid = ROUND(3*RAND()+2,0)
		IF @i%5=0
			SET @actual = 0
		ELSE
			SET @actual = 1
		INSERT INTO CLIENTSERVICE VALUES(@cid, @sid, @actual)
		SET @i = @i + 1;
		IF @@ERROR <> 0
			ROLLBACK
	END
COMMIT
END

DELETE FROM CLIENTSERVICE
SELECT COUNT(*) FROM CLIENTSERVICE
SELECT * FROM ADDSERVISE

CREATE INDEX CLIENTSERVICE_NCI ON CLIENTSERVICE(CLIENT_ID)
DROP INDEX CLIENTSERVICE_NCI ON CLIENTSERVICE
SELECT SERVICE_ID FROM CLIENTSERVICE WHERE CLIENTSERVICE.CLIENT_ID = 256