CREATE DATABASE hotel;
GO
USE hotel;
GO

CREATE TABLE CLIENT(
ID INT PRIMARY KEY IDENTITY,
FIRST_NAME NVARCHAR(30) UNIQUE, 
MAIL VARCHAR(50) MASKED WITH (FUNCTION = 'email()') NOT NULL UNIQUE CHECK (MAIL LIKE '%mail.ru' OR MAIL LIKE '%gmail.com') ,
PASWRD VARBINARY(256) NOT NULL
)

CREATE TABLE ROOM(
ROOM_NUMBER SMALLINT  PRIMARY KEY CHECK(ROOM_NUMBER BETWEEN 100 AND 130 OR
										ROOM_NUMBER BETWEEN 200 AND 230 OR
										ROOM_NUMBER BETWEEN 300 AND 330 OR
										ROOM_NUMBER BETWEEN 400 AND 430 OR
										ROOM_NUMBER BETWEEN 500 AND 530),
ROOM_TYPE NVARCHAR(20) NOT NULL CHECK (ROOM_TYPE LIKE 'Одноместный' OR ROOM_TYPE LIKE 'Двуместный' OR ROOM_TYPE LIKE 'Семейный'),
COST MONEY NOT NULL,
ISAVALIABLE BIT 
)

CREATE TABLE ADDSERVISE(
ID INT PRIMARY KEY IDENTITY,
SERV_NAME VARCHAR(30) NOT NULL UNIQUE,
DESCR TEXT NULL,
COST MONEY NOT NULL
) 

CREATE TABLE CLIENTSERVICE(
ID INT PRIMARY KEY IDENTITY,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(ID),
SERVICE_ID INT FOREIGN KEY REFERENCES ADDSERVISE(ID),
ACTUAL BIT NOT NULL
)

CREATE TABLE RESERVATION(
ID INT PRIMARY KEY IDENTITY,
ROOM_NUMBER SMALLINT FOREIGN KEY REFERENCES ROOM(ROOM_NUMBER),
COMMING datetime NOT NULL,
LEAVING datetime NOT NULL,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(ID),
)

GO
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE CLIENT;
DROP TABLE CLIENTSERVICE;
DROP TABLE ADDSERVISE;


